spring.application.name=backend


spring.profiles.active=dev


app.jwt.secret=PathFinderSecretKey2026PathFinderSecretKey2026
app.jwt.expiration-ms=86400000


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.security.oauth2.client.registration.google.client-id=test-client-id
spring.security.oauth2.client.registration.google.client-secret=test-client-secret
app.oauth2.authorized-redirect-uris=http://localhost:3000/oauth2/redirect