#application-prod.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

server.forward-headers-strategy=FRAMEWORK

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/{registrationId}

app.oauth2.authorized-redirect-uris=${FRONTEND_URL}/home


spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB


logging.level.root=WARN
logging.level.com.pathfinder=INFO

# AWS S3

aws.region=${AWS_REGION}
aws.bucket-name=${AWS_BUCKET_NAME}
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}

# Gemini AI
ai.gemini.enabled=true
ai.gemini.api-key=AQ.Ab8RN6KbRhB7BjwofINEUQ2UQW-EQeFjpbPdVnzP0cOfxgO0sg
ai.gemini.model=gemini-2.5-flash
ai.gemini.timeout-ms=90000
ai.gemini.max-output-tokens=2000
