import { SkillPath } from "./types";

export const mockSkillPaths: SkillPath[] = [
    {
        id: "skillpath-rrhh-gestion-001",
        areaId: "recursos-humanos",
        areaName: "Recursos Humanos",
        subareaId: "gestion-desempeno",
        subareaName: "Gestión del Desempeño",
        title: "Scrum Master Professional Certificate",
        platform: "Coursera",
        description:
            "Aprende fundamentos de Scrum, gestión ágil de equipos y prácticas para mejorar la coordinación del trabajo en entornos colaborativos.",
        difficulty: "INTERMEDIO",
        durationLabel: "6 semanas",
        xp: 180,
        progressPercentage: 60,
        status: "EN_PROGRESO",
        skills: [
            { id: "skill-agile", name: "Gestión ágil" },
            { id: "skill-teamwork", name: "Trabajo en equipo" },
            { id: "skill-planning", name: "Planificación" },
        ],
        externalUrl: "https://www.coursera.org/",
        isRecommended: true,
    },
    {
        id: "skillpath-rrhh-gestion-002",
        areaId: "recursos-humanos",
        areaName: "Recursos Humanos",
        subareaId: "gestion-desempeno",
        subareaName: "Gestión del Desempeño",
        title: "Kanban Fundamentals",
        platform: "Udemy",
        description:
            "Desarrolla habilidades para organizar flujos de trabajo, visualizar tareas y mejorar la productividad de equipos mediante tableros Kanban.",
        difficulty: "BASICO",
        durationLabel: "4 horas",
        xp: 120,
        progressPercentage: 0,
        status: "DISPONIBLE",
        skills: [
            { id: "skill-organization", name: "Organización" },
            { id: "skill-productivity", name: "Productividad" },
            { id: "skill-process", name: "Mejora de procesos" },
        ],
        externalUrl: "https://www.udemy.com/",
        isRecommended: true,
    },
    {
        id: "skillpath-rrhh-gestion-003",
        areaId: "recursos-humanos",
        areaName: "Recursos Humanos",
        subareaId: "gestion-desempeno",
        subareaName: "Gestión del Desempeño",
        title: "Effective Communication Skills",
        platform: "LinkedIn Learning",
        description:
            "Fortalece tu comunicación profesional para brindar retroalimentación, coordinar reuniones y transmitir ideas con claridad.",
        difficulty: "BASICO",
        durationLabel: "2 horas",
        xp: 100,
        progressPercentage: 100,
        status: "CERTIFICADO_PENDIENTE",
        skills: [
            { id: "skill-communication", name: "Comunicación efectiva" },
            { id: "skill-feedback", name: "Retroalimentación" },
            { id: "skill-leadership", name: "Liderazgo" },
        ],
        externalUrl: "https://www.linkedin.com/learning/",
        isRecommended: true,
        evidence: {
            id: "evidence-rrhh-gestion-003",
            fileName: "certificado-comunicacion.pdf",
            status: "PENDIENTE",
            uploadedAt: "2026-06-01",
        },
    },
    {
        id: "skillpath-rrhh-gestion-004",
        areaId: "recursos-humanos",
        areaName: "Recursos Humanos",
        subareaId: "gestion-desempeno",
        subareaName: "Gestión del Desempeño",
        title: "People Analytics Essentials",
        platform: "edX",
        description:
            "Conoce los fundamentos de analítica aplicada a Recursos Humanos para interpretar datos, indicadores y tendencias de desempeño.",
        difficulty: "INTERMEDIO",
        durationLabel: "5 semanas",
        xp: 200,
        progressPercentage: 0,
        status: "DISPONIBLE",
        skills: [
            { id: "skill-analytics", name: "People Analytics" },
            { id: "skill-data", name: "Análisis de datos" },
            { id: "skill-kpi", name: "Indicadores de desempeño" },
        ],
        externalUrl: "https://www.edx.org/",
        isRecommended: true,
    },
    {
        id: "skillpath-rrhh-seleccion-001",
        areaId: "recursos-humanos",
        areaName: "Recursos Humanos",
        subareaId: "seleccion-talento",
        subareaName: "Selección de Talento",
        title: "Recruiting Foundations",
        platform: "LinkedIn Learning",
        description:
            "Aprende conceptos base de reclutamiento, entrevistas, análisis de perfiles y comunicación con candidatos.",
        difficulty: "BASICO",
        durationLabel: "3 horas",
        xp: 110,
        progressPercentage: 0,
        status: "DISPONIBLE",
        skills: [
            { id: "skill-recruiting", name: "Reclutamiento" },
            { id: "skill-interview", name: "Entrevistas" },
            { id: "skill-profile-analysis", name: "Análisis de perfiles" },
        ],
        externalUrl: "https://www.linkedin.com/learning/",
        isRecommended: false,
    },
];