name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar variables
        run: |
          echo "HOST=${{ secrets.EC2_HOST_DEV }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.EC2_USER_DEV }}" >> $GITHUB_ENV
          echo "KEY<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.EC2_SSH_KEY_DEV }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ env.KEY }}
          script: |

            echo "================================="
            echo " INICIANDO DEPLOY DEVELOP "
            echo "================================="

            cd /home/ubuntu/Proyecto-5-PathFinder

            echo "Actualizando repositorio..."
            git fetch --all
            git reset --hard origin/develop

            echo "Deteniendo contenedores..."
            docker-compose down

            echo "Limpiando imágenes Docker antiguas..."
            docker system prune -af

            echo "Construyendo frontend..."
            docker-compose build frontend

            echo "Construyendo backend..."
            docker-compose build backend

            echo "Levantando servicios..."
            docker-compose up -d

            echo "Verificando contenedores..."
            docker ps

            echo "================================="
            echo " DEPLOY COMPLETADO "
            echo "================================="

