name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Detectar cambios
        id: changes
        run: |

          echo "Detectando cambios..."

          FRONT_CHANGED=false
          BACK_CHANGED=false

          git fetch origin develop

          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)

          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep '^frontend/'; then
            FRONT_CHANGED=true
          fi

          if echo "$CHANGED_FILES" | grep '^backend/'; then
            BACK_CHANGED=true
          fi

          echo "FRONT_CHANGED=$FRONT_CHANGED" >> $GITHUB_ENV
          echo "BACK_CHANGED=$BACK_CHANGED" >> $GITHUB_ENV

      - name: Configurar variables
        run: |
          echo "HOST=${{ secrets.EC2_HOST_DEV }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.EC2_USER_DEV }}" >> $GITHUB_ENV
          echo "KEY<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.EC2_SSH_KEY_DEV }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ env.KEY }}
          script: |

            echo "================================="
            echo " INICIANDO DEPLOY DEVELOP "
            echo "================================="

            cd /home/ubuntu/Proyecto-5-PathFinder

            echo "Actualizando repositorio..."
            git fetch --all
            git reset --hard origin/develop

            echo "Deteniendo contenedores..."
            docker-compose down

            echo "Limpiando Docker..."
            docker system prune -af

            if [ "${FRONT_CHANGED}" = "true" ]; then
              echo "Rebuild frontend..."
              docker-compose build frontend
            else
              echo "Frontend sin cambios"
            fi

            if [ "${BACK_CHANGED}" = "true" ]; then
              echo "Rebuild backend..."
              docker-compose build backend
            else
              echo "Backend sin cambios"
            fi

            echo "Levantando servicios..."
            docker-compose up -d

            echo "Contenedores activos:"
            docker ps

            echo "================================="
            echo " DEPLOY COMPLETADO "
            echo "================================="

