name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar variables
        run: |
          echo "HOST=${{ secrets.EC2_HOST_DEV }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.EC2_USER_DEV }}" >> $GITHUB_ENV
          echo "KEY<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.EC2_SSH_KEY_DEV }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ env.KEY }}
          command_timeout: 20m
          script: |

            echo "================================="
            echo " INICIANDO DEPLOY DEVELOP "
            echo "================================="

            cd /home/ubuntu/Proyecto-5-PathFinder

            echo "Actualizando repositorio..."
            git fetch --all
            git reset --hard origin/develop

            echo "Deteniendo contenedores..."
            docker compose down

            echo "Construyendo y levantando servicios..."
            docker compose up -d --build

            echo "Limpiando imágenes huérfanas..."
            docker image prune -f

            echo "Contenedores activos:"
            docker ps

            echo "================================="
            echo " DEPLOY COMPLETADO "
            echo "================================="


